// This file is autogenerated. Changes will be overwritten.
#include <ISMKEKEPX5/moc_SignalBus.cpp>
#include <5UQKT6YRMN/moc_DxgiCaptureEngine.cpp>
#include <5UQKT6YRMN/moc_ICaptureEngine.cpp>
#include <6ZLIQGMFDZ/moc_WindowsOcrEngine.cpp>
#include <LXWRGEM2EP/moc_TranslatorManager.cpp>
#include <FX4633N3NR/moc_HotkeyManager.cpp>
#include <QNGMSASXSL/moc_OverlayManager.cpp>
#include <QNGMSASXSL/moc_TranslationOverlay.cpp>
#include <QD3TEUTSKF/moc_AreaSelector.cpp>
#include <UMXHS6U622/moc_TrayManager.cpp>
